const PDFDocument = require('pdfkit');

class PdfService {
    generatePrescription(consultationData, res) {
        const doc = new PDFDocument({ margin: 50 });

        // Pipe directly to response
        doc.pipe(res);

        // Header
        doc.fontSize(20).text('DHANWANTARI', { align: 'center' });
        doc.fontSize(10).text('AI-Powered Homeopathy', { align: 'center' });
        doc.moveDown();
        doc.fontSize(20).text('Prescription', { align: 'center', underline: true });
        doc.moveDown();

        // Patient Info (Mock if not provided)
        const date = new Date().toLocaleDateString();
        doc.fontSize(12).text(`Date: ${date}`, { align: 'right' });
        doc.text(`Patient: ${consultationData.patientName || 'Guest User'}`);
        doc.moveDown();
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();

        // Symptoms
        if (consultationData.summary) {
            doc.fontSize(14).text('Clinical Summary');
            doc.fontSize(12).text(consultationData.summary);
            doc.moveDown();
        }

        // Remedy
        if (consultationData.remedy) {
            doc.fontSize(14).text('Rx (Remedy)');
            doc.fontSize(16).font('Helvetica-Bold').text(consultationData.remedy);
            doc.font('Helvetica');
            doc.moveDown();
        }

        // Footer
        doc.fontSize(10).text('Generated by Dhanwantari AI', 50, 700, { align: 'center', width: 500 });

        doc.end();
    }
}

module.exports = new PdfService();
